server:
  port: 8084
  servlet:
    context-path: /api
  error:
    include-stacktrace: NEVER

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app2?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update


